#!/bin/sh
# -*- mode: sh -*-

cd `dirname $0`
erl -hidden -noinput -noshell \
    -pa $PWD/ebin $PWD/deps/*/ebin \
    -sname limerickctl@`hostname` \
    -s limerick_ctl -extra limerick@`hostname` $@
